-- 103_kling_media_models.sql
-- Register Kling image/video models and DB-backed routing preferences.

BEGIN;

INSERT INTO llm_models (
    provider,
    model_id,
    display_name,
    family,
    category,
    supports_tools,
    supports_thinking,
    supports_vision,
    supports_coding,
    is_active,
    activation_source,
    linked_key_name,
    metadata,
    execution_model_id,
    discovery_source,
    first_seen_at,
    last_seen_at,
    verification_status,
    capabilities,
    pricing,
    is_selectable,
    is_executable,
    updated_at
)
VALUES
    (
        'kling',
        'kling-v2',
        'Kling v2',
        'kling',
        'media_multimodal',
        false,
        false,
        true,
        false,
        true,
        'manual',
        'KLING_ACCESS_KEY',
        '{"owner":"ceo","source":"migration_103","auth":"jwt_hs256_access_secret"}'::jsonb,
        'kling-v2',
        'manual_seed',
        NOW(),
        NOW(),
        'verified',
        '{"image_generation":true,"video_generation":true,"text_to_video":true,"image_to_video":true,"provider_family":"kling","auth":"jwt_hs256"}'::jsonb,
        '{}'::jsonb,
        true,
        true,
        NOW()
    ),
    (
        'kling',
        'kling-v2-1',
        'Kling v2.1 Image',
        'kling',
        'media_image',
        false,
        false,
        true,
        false,
        true,
        'manual',
        'KLING_ACCESS_KEY',
        '{"owner":"ceo","source":"migration_103","auth":"jwt_hs256_access_secret"}'::jsonb,
        'kling-v2-1',
        'manual_seed',
        NOW(),
        NOW(),
        'verified',
        '{"image_generation":true,"provider_family":"kling","auth":"jwt_hs256"}'::jsonb,
        '{}'::jsonb,
        true,
        true,
        NOW()
    ),
    (
        'kling',
        'kling-v2-new',
        'Kling v2 New Image-to-Image',
        'kling',
        'media_image',
        false,
        false,
        true,
        false,
        true,
        'manual',
        'KLING_ACCESS_KEY',
        '{"owner":"ceo","source":"migration_103","auth":"jwt_hs256_access_secret"}'::jsonb,
        'kling-v2-new',
        'manual_seed',
        NOW(),
        NOW(),
        'verified',
        '{"image_generation":true,"image_to_image":true,"provider_family":"kling","auth":"jwt_hs256"}'::jsonb,
        '{}'::jsonb,
        true,
        true,
        NOW()
    ),
    (
        'kling',
        'kling-2.0',
        'Kling 2.0',
        'kling',
        'media_video',
        false,
        false,
        true,
        false,
        true,
        'manual',
        'KLING_ACCESS_KEY',
        '{"owner":"ceo","source":"migration_103","auth":"jwt_hs256_access_secret"}'::jsonb,
        'kling-2.0',
        'manual_seed',
        NOW(),
        NOW(),
        'verified',
        '{"video_generation":true,"text_to_video":true,"image_to_video":true,"provider_family":"kling","auth":"jwt_hs256"}'::jsonb,
        '{}'::jsonb,
        true,
        true,
        NOW()
    ),
    (
        'kling',
        'kling-v3',
        'Kling v3 Video',
        'kling',
        'media_video',
        false,
        false,
        true,
        false,
        true,
        'manual',
        'KLING_ACCESS_KEY',
        '{"owner":"ceo","source":"migration_103","auth":"jwt_hs256_access_secret"}'::jsonb,
        'kling-v3',
        'manual_seed',
        NOW(),
        NOW(),
        'verified',
        '{"video_generation":true,"text_to_video":true,"image_to_video":true,"provider_family":"kling","auth":"jwt_hs256"}'::jsonb,
        '{}'::jsonb,
        true,
        true,
        NOW()
    )
ON CONFLICT (provider, model_id) DO UPDATE
SET
    display_name = EXCLUDED.display_name,
    family = EXCLUDED.family,
    category = EXCLUDED.category,
    is_active = true,
    activation_source = 'manual',
    linked_key_name = EXCLUDED.linked_key_name,
    metadata = COALESCE(llm_models.metadata, '{}'::jsonb) || EXCLUDED.metadata,
    execution_model_id = EXCLUDED.execution_model_id,
    discovery_source = EXCLUDED.discovery_source,
    last_seen_at = NOW(),
    verification_status = 'verified',
    capabilities = COALESCE(llm_models.capabilities, '{}'::jsonb) || EXCLUDED.capabilities,
    is_selectable = true,
    is_executable = true,
    updated_at = NOW();

INSERT INTO model_routing_preferences (
    route_key,
    provider,
    model_id,
    display_order,
    is_enabled,
    is_default,
    notes,
    updated_at,
    updated_by
)
VALUES
    ('image', 'kling', 'kling-v2', 70, true, false, 'Kling text-to-image route; uses JWT generated from KLING_ACCESS_KEY/KLING_SECRET_KEY.', NOW(), 'migration_103'),
    ('image', 'kling', 'kling-v2-1', 71, true, false, 'Kling v2.1 text-to-image route; uses JWT generated from KLING_ACCESS_KEY/KLING_SECRET_KEY.', NOW(), 'migration_103'),
    ('image', 'kling', 'kling-v2-new', 72, true, false, 'Kling image-to-image route; pass image/image_url in input_refs.', NOW(), 'migration_103'),
    ('video', 'kling', 'kling-2.0', 49, true, false, 'Kling 2.0 text-to-video/image-to-video route; adapter maps execution to Kling v2 model_name.', NOW(), 'migration_103'),
    ('video', 'kling', 'kling-v2', 50, true, false, 'Kling text-to-video/image-to-video route; pass image/image_url for image2video.', NOW(), 'migration_103'),
    ('video', 'kling', 'kling-v3', 51, true, false, 'Kling v3 video route; pass image/image_url for image2video.', NOW(), 'migration_103')
ON CONFLICT (route_key, provider, model_id) DO UPDATE
SET
    display_order = EXCLUDED.display_order,
    is_enabled = true,
    notes = EXCLUDED.notes,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by;

COMMIT;
