#!/bin/bash
# 오비서(ACCT) 카페24 앱 전용 출구 프록시. 허용 목적지: ACCT_EGRESS_ALLOW (기본 api.clobe.ai:443) 뿐.
#
#   acct_egress_proxy.sh render <dir>   tinyproxy.conf / allow.filter / allow.list 를 <dir> 에 쓴다 (docker 호출 없음)
#   acct_egress_proxy.sh up             render -> 이미지 확인/빌드 -> 네트워크 확인 -> 프록시 컨테이너 (재)생성
#   acct_egress_proxy.sh down           프록시 컨테이너만 제거 (네트워크·이미지·설정 파일은 둔다)
#   acct_egress_proxy.sh status         컨테이너 상태와 붙은 네트워크를 출력
#
# 프록시 컨테이너는 내부망(acct_net, internal=true)과 외부용 전용 bridge(acct_egress_out) 양쪽에 붙는다.
# 앱(--network container:acct-pg)은 내부망 DNS 이름 acct-egress-proxy:8888 로만 나간다.
# 임시 조치용 네트워크 acct_egress 와 이름이 다르다 — 그쪽은 문서 절차에서 제거된다.
#
# 허용 규칙(fail-closed):
#   - 항목은 호스트명 또는 호스트명:443. 443 이외의 포트, 와일드카드, IP 주소는 거부한다.
#     tinyproxy 는 호스트와 포트를 따로 걸러서 (호스트 x 포트) 곱집합이 되므로 포트는 443 으로 고정한다.
#   - 목록이 비면 거부(전부 차단 상태로 뜨지 않고 실패).
#   - 시크릿은 다루지 않는다.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EGRESS_NAME="${ACCT_EGRESS_NAME:-acct-egress-proxy}"
EGRESS_ALLOW="${ACCT_EGRESS_ALLOW:-api.clobe.ai:443}"
INTERNAL_NET="${ACCT_EGRESS_INTERNAL_NET:-acct_net}"
OUT_NET="${ACCT_EGRESS_OUT_NET:-acct_egress_out}"
EGRESS_IMAGE="${ACCT_EGRESS_IMAGE:-acct-egress-proxy:1}"
CONF_DIR="${ACCT_EGRESS_CONF_DIR:-/root/acct-egress}"
PROXY_PORT=8888

die() { echo "acct_egress_proxy: $*" >&2; exit "${2:-2}"; }

# stdout: 정규화된(소문자, 중복 제거, 정렬) 호스트명 목록. 잘못된 항목이 하나라도 있으면 exit 2.
parse_allowlist() {
    local raw=$1 item host port label last out=() seen=" "
    raw=${raw//,/ }
    for item in $raw; do
        item=${item,,}
        host=${item%%:*}
        port=443
        [[ $item == *:* ]] && port=${item#*:}
        [[ $port == 443 ]] || die "allow entry '$item': only port 443 is supported"
        [[ $host =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]] \
            || die "allow entry '$item': not a plain host name (no wildcards, no IPs)"
        last=${host##*.}
        [[ $last =~ [a-z] ]] || die "allow entry '$item': last label must not be all digits (IP address)"
        label=" $host "
        [[ $seen == *"$label"* ]] && continue
        seen+="$host "
        out+=("$host")
    done
    (( ${#out[@]} > 0 )) || die "allow list is empty (ACCT_EGRESS_ALLOW)"
    printf '%s\n' "${out[@]}" | sort
}

render_conf() { # render_conf <dir>
    local dir=$1 hosts h
    hosts="$(parse_allowlist "$EGRESS_ALLOW")" || exit $?
    mkdir -p "$dir"
    printf '%s\n' "$hosts" > "$dir/allow.list"
    while IFS= read -r h; do
        printf '^%s$\n' "${h//./\\.}"
    done <<<"$hosts" > "$dir/allow.filter"
    cat > "$dir/tinyproxy.conf" <<EOF
# generated by deploy/acct-egress/acct_egress_proxy.sh - do not edit by hand
Port $PROXY_PORT
Listen 0.0.0.0
Timeout 60
User tinyproxy
Group tinyproxy
LogFile "/dev/stdout"
LogLevel Info
MaxClients 32
DisableViaHeader Yes
ConnectPort 443
FilterType ere
FilterURLs Off
FilterDefaultDeny Yes
Filter "/etc/tinyproxy/allow.filter"
EOF
    chmod 644 "$dir/allow.list" "$dir/allow.filter" "$dir/tinyproxy.conf"
}

check_names() {
    [[ $EGRESS_NAME =~ ^acct-egress-proxy[a-z0-9-]*$ ]] || die "container name '$EGRESS_NAME' must start with acct-egress-proxy"
    [[ $OUT_NET != acct_egress ]] || die "ACCT_EGRESS_OUT_NET must not be the temporary network 'acct_egress'"
    [[ $OUT_NET != "$INTERNAL_NET" ]] || die "outbound and internal network must differ"
    [[ $CONF_DIR == /* && $CONF_DIR != / ]] || die "ACCT_EGRESS_CONF_DIR must be an absolute path"
}

cmd_up() {
    check_names
    render_conf "$CONF_DIR"
    local internal
    internal="$(docker network inspect -f '{{.Internal}}' "$INTERNAL_NET" 2>/dev/null)" \
        || die "internal network $INTERNAL_NET not found" 12
    [[ $internal == true ]] || die "network $INTERNAL_NET is not internal=true; refusing" 12
    docker image inspect "$EGRESS_IMAGE" >/dev/null 2>&1 || docker build -q -t "$EGRESS_IMAGE" "$SCRIPT_DIR" >/dev/null
    if docker network inspect "$OUT_NET" >/dev/null 2>&1; then
        [[ $(docker network inspect -f '{{.Internal}}' "$OUT_NET") == false ]] \
            || die "network $OUT_NET exists but is internal; it cannot give the proxy a way out" 12
    else
        docker network create --driver bridge "$OUT_NET" >/dev/null
    fi
    docker rm -f "$EGRESS_NAME" >/dev/null 2>&1 || true
    docker run -d --name "$EGRESS_NAME" --network "$OUT_NET" --restart unless-stopped \
        --read-only --tmpfs /tmp --tmpfs /run \
        --cap-drop ALL --cap-add SETUID --cap-add SETGID --security-opt no-new-privileges \
        --memory 128m --pids-limit 64 \
        -v "$CONF_DIR/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro" \
        -v "$CONF_DIR/allow.filter:/etc/tinyproxy/allow.filter:ro" \
        "$EGRESS_IMAGE" >/dev/null
    docker network connect "$INTERNAL_NET" "$EGRESS_NAME"
    echo "UP $EGRESS_NAME http://$EGRESS_NAME:$PROXY_PORT allow=$(paste -sd, "$CONF_DIR/allow.list")"
}

cmd_down() {
    check_names
    docker rm -f "$EGRESS_NAME" >/dev/null 2>&1 || true
    echo "DOWN $EGRESS_NAME"
}

cmd_status() {
    check_names
    docker inspect -f '{{.State.Status}} restarts={{.RestartCount}} nets={{range $k, $_ := .NetworkSettings.Networks}}{{$k}} {{end}}' "$EGRESS_NAME"
}

main() {
    case ${1:-} in
        render) [[ -n ${2:-} ]] || die "usage: render <dir>"; check_names; render_conf "$2" ;;
        up) cmd_up ;;
        down) cmd_down ;;
        status) cmd_status ;;
        *) die "usage: $0 render <dir> | up | down | status" ;;
    esac
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then main "$@"; fi
